#!/bin/bash
set -e
# cd to self bash script directory
cd $( dirname ${BASH_SOURCE[0]})
. ./activate
echo Running isort src tests
isort src tests
echo Running black src tests
black src tests
echo Running ruff src tests
ruff check src tests
echo Running mypy src
mypy src tests
echo Linting complete!